services:
  # A background worker that consumes a queue
  - type: worker
    name: guildus-auth-backend-express-js-prod
    repo: https://github.com/n-devs/guildus-auth-backend-express-js.git # optional
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile # optional
    dockerContext: .
    branch: main # optional
    autoDeploy: true # optional
    pullRequestPreviewsEnabled: true # optional
