version: "2"

services:
  guildus-auth-backend-express-js:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: n-devs/guildus-auth-backend-express-js
    command: ["pm2-runtime", "ecosystem.config.js"]
    environment:
      - NODE_ENV=development
    ports:
      - 9002:9002
    volumes:
       - ./:/app
    container_name: guildus-auth-backend-express-js
    restart: always
    networks:
      - guildus-auth-backend-express-js-network
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - guildus-auth-backend-express-js-network
    expose:
      - 27017
networks:
  guildus-auth-backend-express-js-network: