name: Render Deploy Action
on: push
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm clean-install
      - name: "Run client unit tests"
        run: npm test
      - name: "Run server unit tests"
        run: npm run test:server
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: https://api.render.com/deploy/srv-cccbq6pa6gdpn5ops7og?key=mIUE6nq9Jcg
    steps:
      - uses: actions/checkout@v2
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: rnd_XiHJzKSmsgpRfXpoGTw1gybS9sQY
          api-key: rnd_XiHJzKSmsgpRfXpoGTw1gybS9sQY