name: Render Deploy Action
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:     # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'  

permissions:
  contents: read

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          name: node-app
          path: .
      - run: npm clean-install
      - name: "Run client unit tests"
        run: npm test
      - name: "Run server unit tests"
        run: npm run test:server

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: https://guildus-auth-backend-express-js.onrender.com
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app 

      - name: Render Deploy Action
        id: dep-ccckthmn6mpkorrendkg
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}